# $URL$
# $Id$

# Where is scummvm will be installed
SCUMMVMPATH=C:/scummvm

EXEEXT	:=.exe

include Makefile

install:   all
	mkdir -p $(SCUMMVMPATH)
	mkdir -p $(SCUMMVMPATH)/tools
	strip dekyra.exe -o $(SCUMMVMPATH)/tools/dekyra.exe
	strip descumm.exe -o $(SCUMMVMPATH)/tools/descumm.exe
	strip desword2.exe -o $(SCUMMVMPATH)/tools/desword2.exe
	cp COPYING $(SCUMMVMPATH)/tools/COPYING.txt
	cp README $(SCUMMVMPATH)/tools/README.txt
	u2d $(SCUMMVMPATH)/tools/*.txt

dist:   install
